name: flutter_ssl_pinning
description: A Flutter plugin for validating SHA-1 or SHA-256 SSL certificate.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: id.co.eyro.flutter_ssl_pinning
        pluginClass: FlutterSslPinningPlugin
      ios:
        pluginClass: FlutterSslPinningPlugin
